export { ChoosePaymentMethod } from './components/ChoosePaymentMethod'
export { Summary } from './components/Summary'
export { Register } from './components/Register'
export { SelectProduct } from './components/SelectProduct'
export { Pix } from './components/Pix'
